name: Deploy IAC
on:
  push:
    branches:
      - "development"
jobs:
  infra_validate:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: terraform init
      run: make init
    - name: terraform validate
      run: make validate
    - name: terraform lint
      run: make lint
  infra_plan:
    needs: infra_validate
    environment:
      name: development
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: terraform init
      run: make init
    - name: terraform plan
      run: make plan
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  infra_apply:
    needs: infra_plan
    environment:
        name: development
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: terraform init
      run: make init
    - name: terraform plan
      run: make plan
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    - name: terraform apply
      run: make apply
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
